modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="oritechmekanism"
version="${version}"
displayName="Oritech Mekanism"
authors="EveryoneMek"
description='''A deployable Oritech processor with original machine layouts and installable addons.'''
[[dependencies.oritechmekanism]]
modId="neoforge"
type="required"
versionRange="[21.1.241,)"
ordering="NONE"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="mekanism"
type="required"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="oritech"
type="required"
versionRange="[1.2.12,1.3)"
ordering="AFTER"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="architectury"
type="required"
versionRange="[13.0.11,14)"
ordering="AFTER"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="geckolib"
type="required"
versionRange="[4.6.6,5)"
ordering="AFTER"
side="BOTH"
[[dependencies.oritechmekanism]]
modId="oritechthings"
type="optional"
versionRange="[0.0.46,)"
ordering="AFTER"
side="BOTH"
