modLoader="javafml"
loaderVersion="[4,)"
license="MIT; upstream dependencies retain their own licenses"

[[mods]]
modId="botanicalmekanism"
version="${version}"
displayName="Botanical Mekanism"
authors="EveryoneMek"
description='''Botanical processing, powered flowers, native spark upgrades and optional Corporea/ME integration.'''

[[mixins]]
config="botanicalmekanism.mixins.json"

[[dependencies.botanicalmekanism]]
modId="neoforge"
type="required"
versionRange="[21.1.241,)"
ordering="NONE"
side="BOTH"

[[dependencies.botanicalmekanism]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.botanicalmekanism]]
modId="mekanism"
type="required"
versionRange="[10.7.19,)"
ordering="AFTER"
side="BOTH"

[[dependencies.botanicalmekanism]]
modId="botania"
type="required"
versionRange="[456-SNAPSHOT]"
ordering="AFTER"
side="BOTH"

[[dependencies.botanicalmekanism]]
modId="jei"
type="optional"
versionRange="[19.27.0.335,20)"
ordering="AFTER"
side="CLIENT"

[[dependencies.botanicalmekanism]]
modId="ae2"
type="optional"
versionRange="[19.2.17,20)"
ordering="AFTER"
side="BOTH"

[[dependencies.botanicalmekanism]]
modId="ae2jeiintegration"
type="optional"
versionRange="[1.2.1,2)"
ordering="AFTER"
side="CLIENT"

[[dependencies.botanicalmekanism]]
modId="appbot"
type="optional"
versionRange="[1.6.0-alpha.3,1.7)"
ordering="AFTER"
side="BOTH"
