modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="mekgravity"
version="${version}"
displayName="Mek Gravity"
authors="EveryoneMek"
description='''Gravitational reactors and artificial miniature suns with long-life fuel, powered containment and high-throughput energy ports.'''
[[mixins]]
config="mekgravity.mixins.json"
[[dependencies.mekgravity]]
modId="neoforge"
type="required"
versionRange="[21.1.241,)"
ordering="NONE"
side="BOTH"
[[dependencies.mekgravity]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.mekgravity]]
modId="mekanism"
type="required"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"
[[dependencies.mekgravity]]
modId="mekanismgenerators"
type="required"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"
