package dev.everyonemek.gravity.corona;
import java.util.EnumMap;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.shapes.*;
/** Generated by generate_coronal_resources.py; matches the thin docking model. */
public final class CoronalShapes {
    private static final EnumMap<Direction,VoxelShape> SHAPES=new EnumMap<>(Direction.class);
    static{
        SHAPES.put(Direction.NORTH,Shapes.or(Block.box(-3.0,-3.0,23.0,19.0,19.0,25.0),Block.box(-3.0,-3.0,22.5,-1.0,19.0,23.0),Block.box(17.0,-3.0,22.5,19.0,19.0,23.0),Block.box(4.0,4.0,16.0,12.0,12.0,24.0),Block.box(0.0,0.0,10.0,16.0,3.0,18.0),Block.box(0.0,13.0,10.0,16.0,16.0,18.0),Block.box(0.0,3.0,10.0,3.0,13.0,18.0),Block.box(13.0,3.0,10.0,16.0,13.0,18.0),Block.box(3.0,3.0,16.0,13.0,13.0,18.0),Block.box(2.0,2.0,9.0,14.0,3.0,11.0),Block.box(2.0,13.0,9.0,14.0,14.0,11.0),Block.box(2.0,3.0,9.0,3.0,13.0,11.0),Block.box(13.0,3.0,9.0,14.0,13.0,11.0),Block.box(0.0,0.0,10.0,1.0,16.0,18.0),Block.box(15.0,0.0,10.0,16.0,16.0,18.0)));
        SHAPES.put(Direction.EAST,Shapes.or(Block.box(-9.0,-3.0,-3.0,-7.0,19.0,19.0),Block.box(-7.0,-3.0,-3.0,-6.5,19.0,-1.0),Block.box(-7.0,-3.0,17.0,-6.5,19.0,19.0),Block.box(-8.0,4.0,4.0,0.0,12.0,12.0),Block.box(-2.0,0.0,0.0,6.0,3.0,16.0),Block.box(-2.0,13.0,0.0,6.0,16.0,16.0),Block.box(-2.0,3.0,0.0,6.0,13.0,3.0),Block.box(-2.0,3.0,13.0,6.0,13.0,16.0),Block.box(-2.0,3.0,3.0,0.0,13.0,13.0),Block.box(5.0,2.0,2.0,7.0,3.0,14.0),Block.box(5.0,13.0,2.0,7.0,14.0,14.0),Block.box(5.0,3.0,2.0,7.0,13.0,3.0),Block.box(5.0,3.0,13.0,7.0,13.0,14.0),Block.box(-2.0,0.0,0.0,6.0,16.0,1.0),Block.box(-2.0,0.0,15.0,6.0,16.0,16.0)));
        SHAPES.put(Direction.SOUTH,Shapes.or(Block.box(-3.0,-3.0,-9.0,19.0,19.0,-7.0),Block.box(17.0,-3.0,-7.0,19.0,19.0,-6.5),Block.box(-3.0,-3.0,-7.0,-1.0,19.0,-6.5),Block.box(4.0,4.0,-8.0,12.0,12.0,0.0),Block.box(0.0,0.0,-2.0,16.0,3.0,6.0),Block.box(0.0,13.0,-2.0,16.0,16.0,6.0),Block.box(13.0,3.0,-2.0,16.0,13.0,6.0),Block.box(0.0,3.0,-2.0,3.0,13.0,6.0),Block.box(3.0,3.0,-2.0,13.0,13.0,0.0),Block.box(2.0,2.0,5.0,14.0,3.0,7.0),Block.box(2.0,13.0,5.0,14.0,14.0,7.0),Block.box(13.0,3.0,5.0,14.0,13.0,7.0),Block.box(2.0,3.0,5.0,3.0,13.0,7.0),Block.box(15.0,0.0,-2.0,16.0,16.0,6.0),Block.box(0.0,0.0,-2.0,1.0,16.0,6.0)));
        SHAPES.put(Direction.WEST,Shapes.or(Block.box(23.0,-3.0,-3.0,25.0,19.0,19.0),Block.box(22.5,-3.0,17.0,23.0,19.0,19.0),Block.box(22.5,-3.0,-3.0,23.0,19.0,-1.0),Block.box(16.0,4.0,4.0,24.0,12.0,12.0),Block.box(10.0,0.0,0.0,18.0,3.0,16.0),Block.box(10.0,13.0,0.0,18.0,16.0,16.0),Block.box(10.0,3.0,13.0,18.0,13.0,16.0),Block.box(10.0,3.0,0.0,18.0,13.0,3.0),Block.box(16.0,3.0,3.0,18.0,13.0,13.0),Block.box(9.0,2.0,2.0,11.0,3.0,14.0),Block.box(9.0,13.0,2.0,11.0,14.0,14.0),Block.box(9.0,3.0,13.0,11.0,13.0,14.0),Block.box(9.0,3.0,2.0,11.0,13.0,3.0),Block.box(10.0,0.0,15.0,18.0,16.0,16.0),Block.box(10.0,0.0,0.0,18.0,16.0,1.0)));
    }
    public static VoxelShape get(Direction facing){return SHAPES.getOrDefault(facing,SHAPES.get(Direction.NORTH));}
    private CoronalShapes(){}
}
