"""Open, low-poly flare restraint. Reuses original 16px textures; no bitmap drawing."""
import math


def generate(resources, write):
    directory=resources/'assets/mekgravity/models/item'
    frame=[]

    def rotate(p):
        x,y,z=p
        a,b=math.radians(25),math.radians(-20)
        y,z=y*math.cos(a)-z*math.sin(a),y*math.sin(a)+z*math.cos(a)
        return (x*math.cos(b)-y*math.sin(b),x*math.sin(b)+y*math.cos(b),z)

    def ring(angle,r,h):return rotate((r*math.cos(angle),r*math.sin(angle),h))

    def face(target,points,material,normal,uv=(0,.375,1,.625)):
        a,b,c=points[:3];d=[b[i]-a[i] for i in range(3)];e=[c[i]-a[i] for i in range(3)]
        cross=[d[1]*e[2]-d[2]*e[1],d[2]*e[0]-d[0]*e[2],d[0]*e[1]-d[1]*e[0]]
        assert sum(n*n for n in cross)>1e-12, 'Degenerate flare face'
        u,v,U,V=uv;tex=[(u,v),(U,v),(U,V),(u,V)]
        if sum(cross[i]*normal[i] for i in range(3))<0:points=points[::-1];tex=tex[::-1]
        target.append((material,points,tex))

    # A 0.6px band replaces two 10x10px lid slabs. Its octagonal inner edge
    # stays outside the rotating 4.8px-radius core, including chord midpoints.
    inner,outer,half_depth=5.8,6.4,.4
    assert inner*math.cos(math.pi/8)>4.8
    for i in range(8):
        a,b=i*math.tau/8,(i+1)*math.tau/8;mid=(a+b)/2
        for h,sign in [(half_depth,1),(-half_depth,-1)]:
            face(frame,[ring(a,inner,h),ring(b,inner,h),ring(b,outer,h),ring(a,outer,h)],'steel',rotate((0,0,sign)))
        for radius,sign,material in [(inner,-1,'dark'),(outer,1,'steel')]:
            face(frame,[ring(a,radius,-half_depth),ring(b,radius,-half_depth),ring(b,radius,half_depth),ring(a,radius,half_depth)],material,rotate((sign*math.cos(mid),sign*math.sin(mid),0)))

    # Opposed small pole shoes keep a Mek silhouette without enclosing the orb.
    for sign in [-1,1]:
        x,X=(5.7,7.1) if sign>0 else (-7.1,-5.7);y,Y=-1.35,1.35;z,Z=-.85,.85
        for points,normal,material in [
            ([(x,y,z),(x,Y,z),(x,Y,Z),(x,y,Z)],(-1,0,0),'dark' if sign>0 else 'steel'),
            ([(X,y,z),(X,Y,z),(X,Y,Z),(X,y,Z)],(1,0,0),'steel' if sign>0 else 'dark'),
            ([(x,y,z),(X,y,z),(X,y,Z),(x,y,Z)],(0,-1,0),'dark'),
            ([(x,Y,z),(X,Y,z),(X,Y,Z),(x,Y,Z)],(0,1,0),'steel'),
            ([(x,y,z),(X,y,z),(X,Y,z),(x,Y,z)],(0,0,-1),'steel'),
            ([(x,y,Z),(X,y,Z),(X,Y,Z),(x,Y,Z)],(0,0,1),'steel')]:
            face(frame,[rotate(p) for p in points],material,rotate(normal))
        face(frame,[rotate((sign*7.12,j,k)) for j,k in [(-.6,-.3),(.6,-.3),(.6,.3),(-.6,.3)]],'lamp',rotate((sign,0,0)),(7/16,7/16,8/16,8/16))

    # Shader-off fallback uses the same rounded silhouette and frame.
    fallback=list(frame)
    faces=[lambda u,v:(1,1-2*v,1-2*u),lambda u,v:(-1,1-2*v,2*u-1),
           lambda u,v:(2*u-1,1,2*v-1),lambda u,v:(2*u-1,-1,1-2*v),
           lambda u,v:(2*u-1,1-2*v,1),lambda u,v:(1-2*u,1-2*v,-1)]
    for mapping in faces:
        for row in range(4):
            for col in range(4):
                u,v,U,V=col/4,row/4,(col+1)/4,(row+1)/4
                points=[]
                for a,b in [(u,v),(U,v),(U,V),(u,V)]:
                    x,y,z=mapping(a,b)
                    points.append((4.6*x*math.sqrt(1-y*y/2-z*z/2+y*y*z*z/3),4.8*y*math.sqrt(1-z*z/2-x*x/2+z*z*x*x/3),4.6*z*math.sqrt(1-x*x/2-y*y/2+x*x*y*y/3)))
                face(fallback,points,'surface',[sum(p[i] for p in points) for i in range(3)],(u,v,U,V))

    for name,mesh in [('flare_cell_frame',frame),('flare_cell_fallback',fallback)]:
        rows=['# Original MekGravity open flare restraint; generated by tools/flare_cell_mesh.py.','mtllib flare_cell.mtl'];index=0
        for material,points,uvs in mesh:
            rows.append('usemtl '+material)
            for point,uv in zip(points,uvs):
                assert all(-8<v<8 for v in point), 'Flare escaped item bounds'
                rows.append('v '+' '.join(f'{v/16+.5:.7f}' for v in point));rows.append('vt '+' '.join(f'{v:.7f}' for v in uv))
            rows.append('f '+' '.join(f'{i}/{i}' for i in range(index+1,index+5)));index+=4
        (directory/(name+'.obj')).write_text('\n'.join(rows)+'\n',encoding='utf-8',newline='\n')
        write('assets/mekgravity/models/item/'+name+'.json',{'parent':'minecraft:block/block','loader':'neoforge:obj',
              'model':'mekgravity:models/item/'+name+'.obj','mtl_override':'mekgravity:models/item/flare_cell.mtl',
              'automatic_culling':False,'shade_quads':True,'emissive_ambient':True,'flip_v':False,'ambientocclusion':False,
              'textures':{'steel':'mekgravity:block/orb_steel','dark':'mekgravity:block/orb_inner','lamp':'mekgravity:block/sun_collector_active',
                          'surface':'mekgravity:block/stellar_surface_particle','particle':'mekgravity:block/stellar_surface_particle'}})
    (directory/'flare_cell.mtl').write_text('\n\n'.join(f'newmtl {name}\nKa {ambient} {ambient} {ambient}\nKd 1 1 1\nmap_Kd #{name}' for name,ambient in [('steel',0),('dark',0),('lamp',1),('surface',1)])+'\n',encoding='utf-8',newline='\n')
    print(f'Flare restraint: {len(frame)} quads; spherical fallback: {len(fallback)} quads; core clearance and item bounds valid.')
