"""Five optional machine models and recipes, built from existing original materials."""
import json
from generate_solar_resources import ROOT,RES,write,box,mechanical
from generate_coronal_resources import outer_surface
from runtime_geometry import turn

KINDS=['flare_captor','gravity_forge','core_tuner','gravity_node','stellar_observatory']
LABELS=[('耀斑捕获器','Flare Captor'),('引力锻造舱','Gravity Forge'),('核心调谐器','Core Tuner'),('引力物流节点','Gravity Logistics Node'),('恒星观测站','Stellar Observatory')]
def build():
    shapes=[]
    for index,name in enumerate(KINDS):
        variants={}
        for active in [False,True]:
            e=[box([0,0,0],[16,3,16],'#dark',[0,0,16,10]),box([1,0,1],[15,1,15],'#steel',[0,6,16,10])]
            if index==0:
                e += [box([2,3,3],[4,14,13],'#steel',[0,6,16,10]),box([12,3,3],[14,14,13],'#steel',[0,6,16,10]),box([4,11,10],[12,14,14],'#dark',[0,0,16,10]),box([5,3,5],[11,5,11],'#shell',[3,3,13,13])]
            elif index==1:
                e += [box([0,3,0],[3,16,16],'#dark',[0,0,16,10]),box([13,3,0],[16,16,16],'#dark',[0,0,16,10]),box([3,13,0],[13,16,16],'#shell',[3,3,13,13]),box([4,11,5],[12,13,13],'#steel',[0,6,16,10]),box([4,3,5],[12,5,13],'#steel',[0,6,16,10]),box([3,3,13],[13,13,16],'#dark',[0,11,16,16])]
            elif index==2:
                e += [box([1,3,7],[15,7,15],'#shell',[3,3,13,13]),box([2,7,9],[14,15,13],'#dark',[0,11,16,16]),box([1,7,9],[2,16,13],'#steel',[0,6,16,10]),box([14,7,9],[15,16,13],'#steel',[0,6,16,10])]
            elif index==3:
                e += [box([1,3,3],[4,15,13],'#steel',[0,6,16,10]),box([12,3,3],[15,15,13],'#steel',[0,6,16,10]),box([4,12,3],[12,15,13],'#dark',[0,0,16,10]),box([4,3,3],[12,4,13],'#dark',[0,0,16,10]),box([0,5,6],[1,11,12],'#shell',[3,3,13,13]),box([15,5,6],[16,11,12],'#shell',[3,3,13,13])]
            else:
                e += [box([5,3,8],[11,9,13],'#steel',[0,6,16,10]),box([1,7,8],[15,16,12],'#dark',[0,11,16,16]),box([0,7,8],[1,16,12],'#shell',[3,3,13,13]),box([15,7,8],[16,16,12],'#shell',[3,3,13,13]),box([1,15,8],[15,16,12],'#steel',[0,6,16,10])]
            for x in [2,12]:
                light=box([x,1,-.02],[x+2,2,.1],'#lamp',[7,7,8,8]);
                if active:
                    for face in light['faces'].values():face['neoforge_data']={'block_light':12,'ambient_occlusion':False}
                e.append(light)
            model=mechanical(outer_surface(e));model['textures']['particle']='mekgravity:block/orb_inner';model['textures']['lamp']='mekgravity:block/sun_collector_active' if active else 'mekgravity:block/sun_collector'
            variant=name+('_active' if active else '')
            write(f'assets/mekgravity/models/block/{variant}.json',model)
            for facing,y in [('north',0),('east',90),('south',180),('west',270)]:variants[f'facing={facing},active={str(active).lower()}']={'model':'mekgravity:block/'+variant,'y':y}
        shape_names=['CAPTOR','FORGE','TUNER','NODE','OBSERVATORY']
        for direction in ['north','east','south','west']:
            bounds=[]
            for element in e[:-2]:
                corners=[turn([x/16,y/16,z/16],direction) for x in (element['from'][0],element['to'][0]) for y in (element['from'][1],element['to'][1]) for z in (element['from'][2],element['to'][2])]
                lo=[min(p[i] for p in corners)*16 for i in range(3)];hi=[max(p[i] for p in corners)*16 for i in range(3)]
                bounds.append('Block.box('+','.join(str(round(v,4)) for v in lo+hi)+')')
            shapes.append('        SHAPES['+str(index)+']['+str(['north','east','south','west'].index(direction))+']=Shapes.or('+','.join(bounds)+');')
        write(f'assets/mekgravity/blockstates/{name}.json',{'variants':variants})
        write(f'assets/mekgravity/models/item/{name}.json',{'parent':'mekgravity:block/'+name})
        write(f'data/mekgravity/loot_table/blocks/{name}.json',{'type':'minecraft:block','pools':[{'rolls':1,'entries':[{'type':'minecraft:item','name':'mekgravity:'+name,'functions':[{'function':'minecraft:copy_components','source':'block_entity','include':['mekanism:items','mekanism:owner','mekanism:security','mekanism:redstone_control','mekgravity:orbital_module','minecraft:custom_name']}]}],'conditions':[{'condition':'minecraft:survives_explosion'}]}]})
    java='package dev.everyonemek.gravity.expansion;\nimport net.minecraft.core.Direction;\nimport net.minecraft.world.level.block.Block;\nimport net.minecraft.world.phys.shapes.*;\n/** Generated by generate_module_resources.py, from the exact solid model boxes. */\npublic final class ModuleShapes {\n    private static final VoxelShape[][] SHAPES=new VoxelShape[5][4];\n    static{\n'+'\n'.join(shapes)+'\n    }\n    public static VoxelShape get(ModuleKind kind,Direction facing){int i=switch(facing){case EAST->1;case SOUTH->2;case WEST->3;default->0;};return SHAPES[kind.ordinal()][i];}\n    private ModuleShapes(){}\n}\n'
    (ROOT/'src/main/java/dev/everyonemek/gravity/expansion/ModuleShapes.java').write_text(java,encoding='utf-8')
    # Reuse pixel materials on small original solid models; no raster repainting.
    for name,e in {
        'field_linker':[box([6,1,6],[10,10,10],'#steel',[0,6,16,10]),box([3,10,6],[6,15,10],'#dark'),box([10,10,6],[13,15,10],'#dark'),box([6,11,7],[10,14,9],'#lamp',[7,7,8,8])],
        'flare_cell':[box([4,3,4],[12,13,12],'#lamp',[7,7,8,8]),box([3,3,3],[13,5,13],'#steel',[0,6,16,10]),box([3,11,3],[13,13,13],'#steel',[0,6,16,10])],
        'stellar_alloy':[box([2,5,4],[14,9,12],'#steel',[0,6,16,10]),box([3,9,5],[13,10,11],'#dark'),box([4,9.9,6],[12,10.1,10],'#lamp',[7,7,8,8])]
    }.items():
        model=mechanical(outer_surface(e));model['textures']['lamp']='mekgravity:block/sun_collector_active';write(f'assets/mekgravity/models/item/{name}.json',model)
    tag=json.loads((RES/'data/minecraft/tags/block/mineable/pickaxe.json').read_text(encoding='utf-8'));tag['values']=sorted(set(tag['values']+['mekgravity:'+n for n in KINDS]));write('data/minecraft/tags/block/mineable/pickaxe.json',tag)
    def craft(name,pattern,items):write(f'data/mekgravity/recipe/{name}.json',{'type':'minecraft:crafting_shaped','pattern':pattern,'key':{k:{'item':v} for k,v in items.items()},'result':{'id':'mekgravity:'+name}})
    craft('field_linker',[' AC',' SB','S  '],{'A':'mekanism:alloy_atomic','B':'mekanism:teleportation_core','C':'mekanism:ultimate_control_circuit','S':'mekanism:ingot_steel'})
    for name,part,alloy in [('flare_captor','mekanism:laser_amplifier','mekanism:alloy_atomic'),('gravity_forge','mekanism:osmium_compressor','mekanism:alloy_atomic'),('core_tuner','mekanism:energy_tablet','mekgravity:stellar_alloy'),('gravity_node','mekanism:teleportation_core','mekgravity:stellar_alloy'),('stellar_observatory','minecraft:comparator','mekanism:alloy_atomic')]:
        craft(name,['ACA','SPS','ACA'],{'A':alloy,'C':'mekanism:ultimate_control_circuit','S':'mekanism:ingot_steel','P':part})
    for name,machine,inputs,result,count,ticks,energy in [
        ('flare','flare_captor',[('mekanism:alloy_atomic',4),('minecraft:quartz',4)],'mekgravity:flare_cell',1,20,50_000_000_000),
        ('stellar_alloy','gravity_forge',[('mekanism:alloy_atomic',4),('mekanism:hdpe_sheet',1),('mekgravity:flare_cell',1)],'mekgravity:stellar_alloy',4,20,2_000_000_000),
        ('stellar_matter','gravity_forge',[('mekgravity:flare_cell',1)],'mekgravity:compressed_stellar_matter',1,40,5_000_000_000)]:
        write(f'data/mekgravity/recipe/orbital/{name}.json',{'type':'mekgravity:orbital_processing','machine':machine,'inputs':[{'ingredient':{'item':item},'count':n} for item,n in inputs],'result':{'id':result,'count':count},'ticks':ticks,'energy':energy,'tier':0})
    shader=json.loads((RES/'assets/mekgravity/shaders/core/coronal_processing.json').read_text(encoding='utf-8'));shader['vertex']=shader['fragment']='mekgravity:orbital_module';write('assets/mekgravity/shaders/core/orbital_module.json',shader)
    words={
      'burst_hint':('核心运行且缓存未满，消耗1晶核。最长20秒升载，80秒后可再触发。','Requires a running core and buffer room. Uses 1 cell; up to 20s burst, 80s reuse delay.'),
      'tuning_0':('正常功率与燃料消耗','Normal power and fuel consumption'),'tuning_1':('发电80%，新批次加工速度×2','80% generation; new processing batches run twice as fast'),'tuning_2':('发电125%，每单位毛电额外消耗15%燃料','125% generation; 15% extra fuel per gross joule'),
      'unlinked':('用场域链接器绑定能量源','Bind a source with the Field Linker'),'range':('链接超出范围或不在同一维度','Link out of range or in another dimension'),
      'unloaded':('等待目标区块加载','Waiting for target chunk'),'missing':('绑定的装置已移除','Bound device is missing'),'access':('没有使用目标装置的权限','Access to target denied'),
      'source_type':('捕获器需太阳，锻造舱需引力堆','Captor needs sun; forge needs gravity reactor'),'linked':('绑定完成','Link established'),
      'output_full':('输出缓存已满','Output buffer full'),'tier':('需要更高等级约束部件','Higher containment tier required'),'energy':('可用储能不足','Insufficient usable energy'),
      'ingredients':('等待原料','Waiting for ingredients'),'running':('正在加工','Processing'),'paused':('已暂停','Paused'),'cold':('源核心未运行','Source core is not running'),
      'peer_missing':('尚未指定有效接收节点','Select a receiving node'),'peer_paused':('接收节点已暂停','Receiving node is paused'),'transferring':('引力传输中','Transferring cargo'),
      'structure':('源结构不完整','Source structure incomplete'),'monitoring':('链接稳定','Link stable'),'receiving':('正在接收物料','Receiving cargo'),
      'select_source':('潜行右键核心装置或接收节点','Sneak-use on a reactor or receiving node'),
      'source_selected':('已记录能量源 %s','Source selected: %s'),'node_selected':('已记录接收节点 %s','Receiver selected: %s'),
      'link_failed':('绑定失败：检查类型、距离和权限','Link failed: check type, range and access'),
      'linker_hint':('潜行右键记录装置，右键模块绑定。','Sneak-use to select a device; use on a module to bind.'),'selected':('已记录：%s · %s','Selected: %s · %s'),
      'progress':('进度 %s%%','Progress %s%%'),'paid':('加工耗能：%s','Processing energy: %s'),'transfer_energy':('传输耗能：%s','Transfer energy: %s'),'pause':('暂停','Pause'),'enable':('启动','Enable'),
      'eject_on':('自动输出：开','Auto-eject: On'),'eject_off':('自动输出：关','Auto-eject: Off'),'profile':('调谐：%s','Tuning: %s'),
      'profile_0':('均衡','Balanced'),'profile_1':('加工聚焦','Processing'),'profile_2':('核心超频','Overclock'),
      'cooldown':('耀斑恢复：%s秒','Flare recovery: %ss'),'burst':('消耗晶核 · 耀斑升载','Use cell · Flare burst'),'burst_left':('耀斑剩余 %s秒','Flare remaining: %ss'),
      'stored':('储能：%s / %s','Energy: %s / %s'),'net':('净发电：%s/t','Net generation: %s/t'),'exported':('外供：%s/t','Exported: %s/t'),
      'signal':('红石输出：%s','Redstone output: %s'),'alarm_0':('告警：储能比例','Signal: energy level'),'alarm_1':('告警：结构或链接异常','Alarm: structure / link'),
      'alarm_2':('告警：燃料不足','Alarm: low fuel'),'alarm_3':('告警：储能不足','Alarm: low energy'),'threshold':('阈值 %s%%','Threshold %s%%'),
      'details':('场域链接与状态','Field Link and Status'),'source_pos':('能量源：%s','Source: %s'),'peer_pos':('接收节点：%s','Receiver: %s'),
      'fuel':('本份燃料：%s','Current fuel: %s'),'spare':('备用燃料：%s份','Spare fuel: %s'),'transferred':('累计送出：%s个','Items sent: %s'),
      'range_hint':('同维度 · 最远%s格','Same dimension · Up to %s blocks'),'profile_hint':('聚焦：加工×2，发电80%','Processing: x2 speed, 80% generation'),
      'unlink':('解除链接','Unlink'),'stock':('库存：%s / %s','Stored: %s / %s'),'input':('原料','Inputs'),'output':('产物','Outputs'),
      'batch':('批量 %s','Batch %s'),'recipe_info':('等级 %s · %s tick · %s','Tier %s · %s ticks · %s')}
    hints=[('绑定运行中的太阳，封装耀斑晶核。','Bind to a running sun to seal flare cells.'),('绑定运行中的引力堆，锻造恒星合金与压缩物质。','Bind to a running gravity reactor to forge stellar alloy and compressed matter.'),('绑定核心以选择调谐，消耗耀斑晶核启动短时升载。','Bind a core to tune it. Consume a flare cell for a temporary burst.'),('绑定能量源与接收节点，跨距离输送物品。','Bind a power source and receiving node to transfer items remotely.'),('绑定装置查看状态，并输出可选红石告警。','Bind a reactor to view its status and emit configurable redstone signals.')]
    for lang,i in [('zh_cn',0),('en_us',1)]:
        data=json.loads((RES/f'assets/mekgravity/lang/{lang}.json').read_text(encoding='utf-8'));data.update({'mekgravity.module.'+k:v[i] for k,v in words.items()})
        for name,label,hint in zip(KINDS,LABELS,hints):
            data['block.mekgravity.'+name]=data['container.mekgravity.'+name]=label[i];data['description.mekgravity.'+name]=hint[i]
        for name,label in [('field_linker',('场域链接器','Field Linker')),('flare_cell',('耀斑晶核','Flare Cell')),('stellar_alloy',('恒星合金','Stellar Alloy'))]:data['item.mekgravity.'+name]=label[i]
        write(f'assets/mekgravity/lang/{lang}.json',data)
    print('Generated five orbital modules, original geometry, recipes and paired translations.')

if __name__=='__main__':build()
