"""Coronal chamber resources. Original existing 16px MekGravity materials, no new bitmap art."""
import copy,json
from generate_solar_resources import RES, write, box, mechanical
from runtime_geometry import exposed_faces

def outer_surface(elements):
    """Bake the cuboid union once; later pieces own the overlapping material.

    Keep the original solid boxes for collision. Render only their exposed faces,
    with cropped source UVs so removing a covered area never stretches its texture.
    """
    solids=[{'lo':[n/16 for n in e['from']], 'hi':[n/16 for n in e['to']], 'material':i} for i,e in enumerate(elements)]
    # Source UV directions used by Minecraft's unrotated cube faces.
    uv_axes={'north':(0,-1,1,-1),'south':(0,1,1,-1),'west':(2,1,1,-1),
             'east':(2,-1,1,-1),'up':(0,1,2,1),'down':(0,1,2,-1)}
    result=[]
    for lo,hi,side,index in exposed_faces(solids):
        source=elements[index];face=copy.deepcopy(source['faces'][side]);uv=face['uv'];cropped=[]
        assert not face.get('rotation'), 'UV remapping expects unrotated source faces'
        for lower in (True,False):
            coords=[]
            for axis,sign,minimum,maximum in ((uv_axes[side][0],uv_axes[side][1],uv[0],uv[2]),(uv_axes[side][2],uv_axes[side][3],uv[1],uv[3])):
                edge=(lo if lower else hi)[axis] if sign>0 else (hi if lower else lo)[axis]
                fraction=(edge-source['from'][axis])/(source['to'][axis]-source['from'][axis])
                if sign<0:fraction=1-fraction
                coords.append(minimum+(maximum-minimum)*fraction)
            cropped+=coords
        face['uv']=cropped
        result.append({'from':lo,'to':hi,'faces':{side:face}})
    return result

def build():
    variants={}
    for active in (False,True):
        # North-facing thin wing dock; the backing plate meets the collector at z=24.
        e=[box([-3,-3,23],[19,19,25],'#dark',[0,0,16,10]),
           box([-3,-3,22.5],[-1,19,23],'#steel',[0,6,16,10]),box([17,-3,22.5],[19,19,23],'#steel',[0,6,16,10]),
           box([4,4,16],[12,12,24],'#dark',[0,11,16,16]),
           box([0,0,10],[16,3,18],'#dark',[0,0,16,10]),box([0,13,10],[16,16,18],'#dark',[0,0,16,10]),
           box([0,3,10],[3,13,18],'#dark',[0,0,16,10]),box([13,3,10],[16,13,18],'#dark',[0,0,16,10]),
           box([3,3,16],[13,13,18],'#dark',[0,11,16,16]),
           box([2,2,9],[14,3,11],'#steel',[0,6,16,10]),box([2,13,9],[14,14,11],'#steel',[0,6,16,10]),
           box([2,3,9],[3,13,11],'#steel',[0,6,16,10]),box([13,3,9],[14,13,11],'#steel',[0,6,16,10])]
        # Narrow pale rails tie into the support metal; the main body stays graphite.
        for x in (0,15):e.append(box([x,0,10],[x+1,16,18],'#shell',[3,3,13,13]))
        for x in (4,10):
            lamp=box([x,1,9.98],[x+2,2,10],'#lamp',[7,7,8,8])
            if active:
                for face in lamp['faces'].values():face['neoforge_data']={'block_light':12,'ambient_occlusion':False}
            e.append(lamp)
        model=mechanical(outer_surface(e));model['textures']['particle']='mekgravity:block/orb_inner';model['textures']['lamp']='mekgravity:block/sun_collector_active' if active else 'mekgravity:block/sun_collector'
        name='coronal_chamber'+('_active' if active else '')
        write(f'assets/mekgravity/models/block/{name}.json',model)
        for face,y in [('north',0),('east',90),('south',180),('west',270)]:variants[f'facing={face},active={str(active).lower()}']={'model':'mekgravity:block/'+name,'y':y}
    from runtime_geometry import turn
    from generate_solar_resources import ROOT
    geometry=e[:-2] # status lights are not part of the collision shape
    shapes=[]
    for face in ['north','east','south','west']:
        bounds=[]
        for element in geometry:
            corners=[turn([x/16,y/16,z/16],face) for x in (element['from'][0],element['to'][0]) for y in (element['from'][1],element['to'][1]) for z in (element['from'][2],element['to'][2])]
            lo=[min(p[i] for p in corners)*16 for i in range(3)];hi=[max(p[i] for p in corners)*16 for i in range(3)]
            bounds.append('Block.box('+','.join(str(round(v,4)) for v in lo+hi)+')')
        shapes.append('        SHAPES.put(Direction.'+face.upper()+',Shapes.or('+','.join(bounds)+'));')
    java='package dev.everyonemek.gravity.corona;\nimport java.util.EnumMap;\nimport net.minecraft.core.Direction;\nimport net.minecraft.world.level.block.Block;\nimport net.minecraft.world.phys.shapes.*;\n/** Generated by generate_coronal_resources.py; matches the thin docking model. */\npublic final class CoronalShapes {\n    private static final EnumMap<Direction,VoxelShape> SHAPES=new EnumMap<>(Direction.class);\n    static{\n'+'\n'.join(shapes)+'\n    }\n    public static VoxelShape get(Direction facing){return SHAPES.getOrDefault(facing,SHAPES.get(Direction.NORTH));}\n    private CoronalShapes(){}\n}\n'
    (ROOT/'src/main/java/dev/everyonemek/gravity/corona/CoronalShapes.java').write_text(java,encoding='utf-8')
    write('assets/mekgravity/blockstates/coronal_chamber.json',{'variants':variants})
    write('assets/mekgravity/models/item/coronal_chamber.json',{'parent':'mekgravity:block/coronal_chamber','display':{'gui':{'rotation':[30,225,0],'translation':[0,0,0],'scale':[.45,.45,.45]}}})
    write('data/mekgravity/loot_table/blocks/coronal_chamber.json',{'type':'minecraft:block','pools':[{'rolls':1,'entries':[{'type':'minecraft:item','name':'mekgravity:coronal_chamber','functions':[{'function':'minecraft:copy_components','source':'block_entity','include':['mekanism:items','mekanism:owner','mekanism:security','mekanism:redstone_control','mekgravity:coronal_work','minecraft:custom_name']}]}],'conditions':[{'condition':'minecraft:survives_explosion'}]}]})
    p=RES/'data/minecraft/tags/block/mineable/pickaxe.json';tag=json.loads(p.read_text(encoding='utf-8'));tag['values']=sorted(set(tag['values']+['mekgravity:coronal_chamber']));write('data/minecraft/tags/block/mineable/pickaxe.json',tag)
    write('data/mekgravity/recipe/coronal_chamber.json',{'type':'minecraft:crafting_shaped','pattern':['ABA','CDC','ABA'],'key':{k:{'item':v} for k,v in {'A':'mekgravity:solar_base','B':'mekanism:alloy_atomic','C':'mekanism:ultimate_control_circuit','D':'mekanism:energized_smelter'}.items()},'result':{'id':'mekgravity:coronal_chamber'}})
    for name,inputs,result,count,ticks,energy,tier in [
        ('infused',[('c:ingots/copper',1,True),('minecraft:redstone',1,False)],'mekanism:alloy_infused',1,40,1_000_000_000,0),
        ('reinforced',[('mekanism:alloy_infused',4,False),('mekanism:enriched_diamond',1,False)],'mekanism:alloy_reinforced',4,60,4_000_000_000,1),
        ('atomic',[('mekanism:alloy_reinforced',2,False),('mekanism:enriched_refined_obsidian',1,False)],'mekanism:alloy_atomic',2,80,8_000_000_000,2)]:
        write(f'data/mekgravity/recipe/coronal_processing/{name}.json',{'type':'mekgravity:coronal_processing','inputs':[{'ingredient':{'tag' if tag else 'item':item},'count':n} for item,n,tag in inputs],'result':{'id':result,'count':count},'ticks':ticks,'energy':energy,'tier':tier})
    shader=json.loads((RES/'assets/mekgravity/shaders/core/stellar_field.json').read_text(encoding='utf-8'));shader['vertex']=shader['fragment']='mekgravity:coronal_processing';write('assets/mekgravity/shaders/core/coronal_processing.json',shader)
    words={'slot_stock':('库存：%s / %s','Stored: %s / %s'),
      'input':('原料','Inputs'),'output':('产物','Outputs'),'batch':('批量 %s','Batch %s'),'progress':('进度 %s%%','Progress %s%%'),
      'paid':('本批已付：%s','Batch paid: %s'),'energy_used':('日冕加工扣能：%s','Coronal batch debit: %s'),
      'unlinked':('贴在采能翼外侧中心，背面朝向采能翼','Attach rear to the outer center of a collector wing'),
      'access':('无权使用这台微缩太阳','No permission to use this sun'),'paused':('加工已暂停','Processing paused'),
      'cold':('等待恒星点燃','Waiting for a hot star'),'energy':('太阳可用储能不足','Insufficient available solar energy'),
      'tier_low':('需要更高级的恒星约束部件','Higher stellar containment tier required'),'no_recipe':('等待可加工原料','Waiting for processable inputs'),
      'output_full':('产物空间不足','Output space full'),'running':('日冕高温加工中','Coronal processing'),
      'stop':('暂停','Pause'),'start':('启动','Start'),'eject_on':('自动输出：开','Auto-eject: On'),'eject_off':('自动输出：关','Auto-eject: Off'),
      'category':('日冕高温加工','Coronal Processing'),'recipe_info':('等级 %s · %s tick · %s','Tier %s · %s ticks · %s')}
    for lang,i in [('zh_cn',0),('en_us',1)]:
        p=RES/f'assets/mekgravity/lang/{lang}.json';data=json.loads(p.read_text(encoding='utf-8'));data.update({'mekgravity.corona.'+k:v[i] for k,v in words.items()})
        for key in ['block.mekgravity.coronal_chamber','container.mekgravity.coronal_chamber']:data[key]=('日冕加工舱','Coronal Processing Chamber')[i]
        data['description.mekgravity.coronal_chamber']=('贴在采能翼外侧中心。消耗太阳储能批量熔炼、精炼合金；侧面及上下进料，正面出料。','Mount outside the center of a collector wing. Uses solar energy for batch smelting and alloy refining. Inputs: sides, top and bottom. Output: front.')[i]
        write(f'assets/mekgravity/lang/{lang}.json',data)
    print('Generated coronal chamber models, loot, recipes, shader definition and translations.')

if __name__=='__main__':build()
