"""Original small material meshes, shared by shader drawing and baked fallback models."""
import math,json

NAMES=['compressed_stellar_matter','stellar_fuel_preform','stellar_fuel','stellar_alloy','stellar_fuel_capsule']

def geometry(kind,segments):
    faces=[]
    def face(points,region,normal):
        a,b,c=points[:3];u=[b[i]-a[i] for i in range(3)];v=[c[i]-a[i] for i in range(3)];n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]
        if sum(n[i]*normal[i] for i in range(3))<0:points=points[::-1];n=[-x for x in n]
        length=math.sqrt(sum(x*x for x in n));assert length>1e-8
        faces.append((points,[x/length for x in n],region))
    def box(a,b,region):
        x,y,z=a;X,Y,Z=b
        for p,n in [([(x,y,z),(x,Y,z),(x,Y,Z),(x,y,Z)],(-1,0,0)),([(X,y,z),(X,Y,z),(X,Y,Z),(X,y,Z)],(1,0,0)),([(x,y,z),(X,y,z),(X,y,Z),(x,y,Z)],(0,-1,0)),([(x,Y,z),(X,Y,z),(X,Y,Z),(x,Y,Z)],(0,1,0)),([(x,y,z),(X,y,z),(X,Y,z),(x,Y,z)],(0,0,-1)),([(x,y,Z),(X,y,Z),(X,Y,Z),(x,Y,Z)],(0,0,1))]:face(p,region,n)
    def cylinder(radius,y,Y,region):
        def p(angle,h):return (8+math.cos(angle)*radius,h,8+math.sin(angle)*radius)
        for i in range(segments):
            a,b=i*math.tau/segments,(i+1)*math.tau/segments;m=(a+b)/2
            face([p(a,y),p(b,y),p(b,Y),p(a,Y)],region,(math.cos(m),0,math.sin(m)))
            for h,sign in [(y,-1),(Y,1)]:face([(8,h,8),p(a,h),p(b,h),(8,h,8)],region,(0,sign,0))
    if kind==0:
        box([4,4,4],[12,12,12],2)
        for x,z in [(3,3),(11.5,3),(3,11.5),(11.5,11.5)]:box([x,5.5,z],[x+1.5,10.5,z+1.5],0)
    elif kind==1:
        box([5.5,4,5.5],[10.5,12,10.5],2);box([5,3,5],[11,4,11],1);box([5,12,5],[11,13,11],0)
        box([4.7,4,7.3],[5.5,12,8.7],0);box([10.5,4,7.3],[11.3,12,8.7],0)
    elif kind in [2,4]:
        cylinder(2.9,5,11,2);cylinder(3.5,2.5,5,0);cylinder(3.5,11,13.5,0);cylinder(1.8,1.5,2.5,1);cylinder(1.8,13.5,14.5,1)
        box([4.2,5,7.5],[5,11,8.5],1);box([11,5,7.5],[11.8,11,8.5],1)
    else:
        rings=[[(2,5,4),(14,5,4),(14,5,12),(2,5,12)],[(2,8.5,4),(14,8.5,4),(14,8.5,12),(2,8.5,12)],[(3,10,5),(13,10,5),(13,10,11),(3,10,11)]]
        face(rings[0],1,(0,-1,0));face(rings[2],0,(0,1,0))
        for r in range(2):
            for i in range(4):j=(i+1)%4;p=[rings[r][i],rings[r][j],rings[r+1][j],rings[r+1][i]];face(p,0,(sum(q[0]-8 for q in p),1 if r else 0,sum(q[2]-8 for q in p)))
        face([(4,10.15,7.4),(12,10.15,7.4),(12,10.15,8.6),(4,10.15,8.6)],2,(0,1,0))
    return faces

def generate(resources,write):
    methods=[];directory=resources/'assets/mekgravity/models/item';directory.mkdir(parents=True,exist_ok=True)
    for kind,name in enumerate(NAMES):
        high=geometry(kind,8)
        for lod,segments in enumerate([8,4]):
            mesh=geometry(kind,segments);values=[]
            for points,normal,region in mesh:
                for p in points:values.append(','.join(f'{x:.7f}F' for x in [*[v/16-.5 for v in p],*normal,float(region)]))
            methods.append(f'    private static float[] mesh{kind}_{lod}(){{return new float[]{{\n'+',\n'.join(values)+'\n    };}\n')
        rows=['# Original material mesh. Generated by tools/stellar_materials.py.','mtllib stellar_material.mtl'];index=0
        for points,normal,region in high:
            rows.append('usemtl '+['steel','dark','energy'][region]);uv=[(0,.375),(1,.375),(1,.625),(0,.625)] if region!=2 else [(0,0),(1,0),(1,1),(0,1)]
            for p,t in zip(points,uv):rows+=['v '+' '.join(f'{x/16:.7f}' for x in p),'vt '+' '.join(map(str,t))]
            rows.append('f '+' '.join(f'{i}/{i}' for i in range(index+1,index+5)));index+=4
        (directory/(name+'_fallback.obj')).write_text('\n'.join(rows)+'\n',encoding='utf-8',newline='\n')
        particle='mekgravity:block/orb_active' if kind==0 else 'mekgravity:block/stellar_surface_particle'
        write('assets/mekgravity/models/item/'+name+'_fallback.json',{'parent':'minecraft:block/block','loader':'neoforge:obj','model':'mekgravity:models/item/'+name+'_fallback.obj','mtl_override':'mekgravity:models/item/stellar_material.mtl','automatic_culling':False,'shade_quads':True,'emissive_ambient':True,'flip_v':False,'ambientocclusion':False,'textures':{'steel':'mekgravity:block/orb_steel','dark':'mekgravity:block/orb_inner','energy':particle,'particle':particle}})
        display={'gui':{'rotation':[20,35,0],'scale':[1,1,1]},'ground':{'translation':[0,3,0],'scale':[.5,.5,.5]},'fixed':{'scale':[.8,.8,.8]},'firstperson_righthand':{'rotation':[0,-30,0],'translation':[0,2,0],'scale':[.8,.8,.8]},'firstperson_lefthand':{'rotation':[0,30,0],'translation':[0,2,0],'scale':[.8,.8,.8]},'thirdperson_righthand':{'scale':[.6,.6,.6]},'thirdperson_lefthand':{'scale':[.6,.6,.6]}}
        write('assets/mekgravity/models/item/'+name+'.json',{'parent':'builtin/entity','gui_light':'front','textures':{'particle':particle},'display':display})
    (directory/'stellar_material.mtl').write_text('\n\n'.join(f'newmtl {n}\nKa {a} {a} {a}\nKd 1 1 1\nmap_Kd #{n}' for n,a in [('steel',0),('dark',0),('energy',1)])+'\n',encoding='utf-8',newline='\n')
    init=','.join('{mesh'+str(k)+'_0(),mesh'+str(k)+'_1()}' for k in range(5))
    java='package dev.everyonemek.gravity.client;\n/** Generated alongside the exact baked fallback geometry. Vertex: XYZ, normal XYZ, material region. */\npublic final class StellarMaterialMesh {\n    private static final float[][][] MESH={'+init+'};\n    public static float[] vertices(int kind,boolean reduced){return MESH[kind][reduced?1:0];}\n'+''.join(methods)+'    private StellarMaterialMesh(){}\n}\n'
    (resources.parent/'java/dev/everyonemek/gravity/client/StellarMaterialMesh.java').write_text(java,encoding='utf-8',newline='\n')
    shader=json.loads((resources/'assets/mekgravity/shaders/core/stellar_surface.json').read_text(encoding='utf-8'));shader['vertex']=shader['fragment']='mekgravity:stellar_material';write('assets/mekgravity/shaders/core/stellar_material.json',shader)
    print('Material quads high/ground: '+', '.join(n+': '+str(len(geometry(i,8)))+'/'+str(len(geometry(i,4))) for i,n in enumerate(NAMES)))
