modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="overloadcore"
version="${version}"
displayName="Overload Core"
authors="EveryoneMek"
description='''A permanently bound industrial core with Mekanism curses and controlled production benefits.'''
[[mixins]]
config="overloadcore.mixins.json"
[[dependencies.overloadcore]]
modId="neoforge"
type="required"
versionRange="[21.1.241,)"
ordering="NONE"
side="BOTH"
[[dependencies.overloadcore]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.overloadcore]]
modId="mekanism"
type="required"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"
[[dependencies.overloadcore]]
modId="mekanismgenerators"
type="optional"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"
[[dependencies.overloadcore]]
modId="curios"
type="required"
versionRange="[9.5.1,10)"
ordering="AFTER"
side="BOTH"
