modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config="forbiddenmekanism.mixins.json"

[[mods]]
modId="forbiddenmekanism"
version="${version}"
displayName="Forbidden Mekanism"
description='''Mekanism automation controllers for the Hephaestus Forge and Clibano.'''

[[dependencies.forbiddenmekanism]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.forbiddenmekanism]]
modId="neoforge"
type="required"
versionRange="[21.1.241,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.forbiddenmekanism]]
modId="mekanism"
type="required"
versionRange="[10.7.19,10.8)"
ordering="AFTER"
side="BOTH"

[[dependencies.forbiddenmekanism]]
modId="forbidden_arcanus"
type="required"
versionRange="[2.6.1,2.7)"
ordering="AFTER"
side="BOTH"

[[dependencies.forbiddenmekanism]]
modId="valhelsia_core"
type="required"
versionRange="[1.1.4,1.2)"
ordering="AFTER"
side="BOTH"
